Add azure pipelines and Docker config files
statisticsnorway/microdata-datastore-version-manager pull request #4
Opened 2021-12-07 08:19 UTC by pawbu

2021-12-07 08:34 UTC, vaskalan requested changes

2021-12-07 08:34 UTC, vaskalan commented on README.md
> +export DATASET_BUILDER_OUTPUT_DIR=/output
A bizarre situation is observed here:
If datastore-version-manager maps /output and /datastore directories, where does it read input files from? /output?
Maybe a better config could be
**export DATASET_BUILDER_OUTPUT_DIR=/input**
datastore-version-manager reads its files from input, which in turn is dataset builders output.
Isn't it better to grasp?

2021-12-07 09:15 UTC, DanielElisenberg commented on README.md
> +export DATASET_BUILDER_OUTPUT_DIR=/output
I agree. Maybe we call this something descriptive rather than IO-based? Like "prepared_datasets_dir" or similar?

2021-12-07 13:33 UTC, pawbu commented on README.md
> +export DATASET_BUILDER_OUTPUT_DIR=/output
As discussed it will be called BUILT_DATASETS_DIR

2021-12-08 12:25 UTC, DanielElisenberg approved these changes
Looks good to me :100:

2021-12-08 12:25 UTC, DanielElisenberg commented on tests/unit/test_commands.py
> +    monkeypatch.setenv('BUILT_DATASETS_DIR', 'tests/resources/built_datasets')
:100:

2021-12-08 12:25 UTC, DanielElisenberg commented on docker-compose.yml
> +version: "2"
docker compose for local testing purposes? 👀

2021-12-08 12:57 UTC, vaskalan approved these changes

2021-12-08 13:18 UTC, pawbu commented on docker-compose.yml
> +version: "2"
The idea is similar as for dataset-builder - with lots of env vars to configure, it's easy to have them in this file here instead of specifying in cmd with docker run

2021-12-08 13:18 UTC, merged